#! /bin/sh

if [ "$SPKG_LOCAL" = "" ]; then
   echo "SPKG_LOCAL undefined ... exiting";
   echo "Maybe run 'qsnake --shell'?"
   exit 1
fi


set -e

# Install executables:
cp dev_appserver.py "$SPKG_LOCAL"/bin/
mkdir -p "$SPKG_LOCAL"/share/google_appengine

# Install the library:
cp -r google lib templates VERSION "$SPKG_LOCAL"/share/google_appengine/
