#! /bin/sh

if [ "$SPKG_LOCAL" = "" ]; then
   echo "SPKG_LOCAL undefined ... exiting";
   echo "Maybe run 'qsnake --shell'?"
   exit 1
fi


set -e

cp dev_appserver.py "$SPKG_LOCAL"/bin/
mkdir -p "$SPKG_LOCAL"/share/google_appengine
cp -r google "$SPKG_LOCAL"/share/google_appengine/
cp -r lib "$SPKG_LOCAL"/share/google_appengine/
cp -r templates "$SPKG_LOCAL"/share/google_appengine/
